---
title: "HW3"
author: "James Waskow and Tessa Lanzel"
date: "2023-03-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import Data
```{r}
choco <- read.csv("https://ds202-at-isu.github.io/labs/data/choco.csv")
head(choco, 25)
```

## Question Set 1
```{r}
print(nrow(choco))
```

```{r}
library(ggplot2)
ggplot(choco, aes(Review.Date)) + geom_bar()
```

## Question Set 2
```{r}
ggplot(choco, aes(Rating)) + geom_histogram(bins = 15)
```
The ratings are bimodal and slightly left skewed, few small end outliers

```{r}
ggplot(choco, aes(Rating, Cocoa.Pct)) + geom_point()
```
Cocoa percentage does not seem to have a large correlation with rating

```{r}
ggplot(dplyr::filter(choco, Company.Location %in% c("U.S.A.", "France", "Canada")), aes(Company.Location, Rating)) + geom_boxplot()
```

## Group Questions
Does bean origin, either Brazil, Madagascar, or Panama, effect ratings?
```{r}
ggplot(dplyr::filter(choco, Specific.Bean.Origin %in% c("Brazil", "Madagascar", "Panama")), aes(Rating, Specific.Bean.Origin)) + geom_boxplot()
```

